#!/bin/sh /etc/rc.common
# Copyright (C) 2024 luci-app-singbox-ui
# This is free software, licensed under the GNU General Public License v2.

USE_PROCD=1
START=99
STOP=99

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/singbox-ui/singbox-ui-memdoc
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param pidfile /var/run/singbox-ui-memdoc.pid
    procd_close_instance
}