name: Build luci-app-singbox-ui from PR
run-name: Build artifact PR ${{ github.event.pull_request.number }}

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest

    outputs:
      ipk_name: ${{ steps.rename.outputs.ipk_name }}

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Build Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          tags: singbox-ui:ci

      - name: Create Docker container
        run: docker create --name singbox-ui singbox-ui:ci

      - name: Copy built .ipk from Docker container
        run: docker cp singbox-ui:/builder/bin/packages/x86_64/luci/. ./bin/

      - name: Rename and move .ipk
        id: rename
        run: |
          mkdir -p ./artifacts
          DATE=$(date +%Y%m%d-%H%M)
          PR_NUM=${{ github.event.pull_request.number }}
          PR_TITLE="${{ github.event.pull_request.title }}"
          SAFE_TITLE=$(echo "$PR_TITLE" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g' | sed -E 's/^-+|-+$//g')
          NEW_NAME="luci-app-singbox-ui-pr-${PR_NUM}-${SAFE_TITLE}-${DATE}.ipk"
          cp ./bin/luci-app-singbox-ui*.ipk "./artifacts/${NEW_NAME}"
          echo "ipk_name=${NEW_NAME}" >> "$GITHUB_OUTPUT"

      - name: Remove Docker container
        run: docker rm singbox-ui

      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: built-ipk
          path: ./artifacts/

  commit:
    name: Commit to main branch
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4.2.2
        with:
          ref: main
          fetch-depth: 0

      - name: Copy new .ipk from previous job artifact
        uses: actions/download-artifact@v4.3.0
        with:
          name: built-ipk
          path: ./new-ipk/

      - name: Copy new .ipk to artifacts directory
        run: |
          mkdir -p artifacts
          cp ./new-ipk/*.ipk ./artifacts/

      - name: Remove old .ipk files (>= 7 days)
        run: |
          for file in artifacts/*.ipk; do
            if [ -f "$file" ]; then
              basename=$(basename "$file")
              date_part=$(echo "$basename" | sed -E 's/.*-([0-9]{8}-[0-9]{4})\.ipk$/\1/')
              if [[ $date_part =~ ^[0-9]{8}-[0-9]{4}$ ]]; then
                ymd=${date_part:0:8}
                hm=${date_part:9:4}
                h=${hm:0:2}
                m=${hm:2:2}
                file_date=$(date -d "${ymd:0:4}-${ymd:4:2}-${ymd:6:2} ${h}:${m}:00" +%s)
                now=$(date +%s)
                diff=$(( (now - file_date) / 86400 ))
                if (( diff >= 7 )); then
                  echo "Deleting old file: $file"
                  rm "$file"
                fi
              fi
            fi
          done

      - name: Update index.txt
        run: |
          shopt -s nullglob
          files=(artifacts/*.ipk)
          if [ ${#files[@]} -eq 0 ]; then
            echo "" > artifacts/index.txt
          else
            printf "%s\n" "${files[@]##*/}" > artifacts/index.txt
          fi

      - name: Commit and push changes
        run: |
          echo "📤 Committing updated .ipk to main"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add artifacts/
          git commit -m "github-actions[bot]: update .ipk from PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push origin HEAD:main
