name: Build packages

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - name: x86_64-snapshot
            target: x86
            subtarget: 64
            sdk_version: snapshot
          - name: x86_64-v23.05.5
            target: x86
            subtarget: 64
            sdk_version: v23.05.5
          - name: arm_cortex-a7-v23.05.5
            target: armvirt
            subtarget: 32
            sdk_version: v23.05.5
          - name: x86_64-v24.10.1
            target: x86
            subtarget: 64
            sdk_version: v24.10.1

    name: Build luci-app-singbox-ui ${{ matrix.build.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --build-arg TARGET=${{ matrix.build.target }} \
            --build-arg SUBTARGET=${{ matrix.build.subtarget }} \
            --build-arg SDK_VERSION=${{ matrix.build.sdk_version }} \
            -t luci-app-singbox-ui:${{ matrix.build.name }} .

      - name: Create container
        run: docker create --name build-${{ matrix.build.name }} luci-app-singbox-ui:${{ matrix.build.name }}

      - name: Copy IPK files
        run: |
          mkdir -p ./output/${{ matrix.build.name }}
          docker cp build-${{ matrix.build.name }}:/sdk/bin/packages ./output/${{ matrix.build.name }}

      - name: Remove container
        run: docker rm build-${{ matrix.build.name }}

      - name: Upload IPKs to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./output/${{ matrix.build.name }}/**/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
