name: Build packages

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build luci-app-singbox-ui
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, mipsel_24kc]
        version: [23.05.5, snapshot]
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            ARCH=${{ matrix.arch }}
            VERSION=${{ matrix.version }}
          tags: singbox-ui:${{ matrix.arch }}-${{ matrix.version }}

      - name: Create Docker container
        run: docker create --name singbox-ui-${{ matrix.arch }}-${{ matrix.version }} singbox-ui:${{ matrix.arch }}-${{ matrix.version }}

      - name: Copy file from Docker container
        run: |
          docker cp singbox-ui-${{ matrix.arch }}-${{ matrix.version }}:/builder/bin/packages/${{ matrix.arch }}/luci/. ./bin/${{ matrix.arch }}-${{ matrix.version }}/

      - name: Filter IPK files
        run: |
          mkdir -p ./filtered-bin
          cp ./bin/${{ matrix.arch }}-${{ matrix.version }}/luci-app-singbox-ui*.ipk ./filtered-bin/luci-app-singbox-ui_${{ matrix.arch }}_${{ matrix.version }}.ipk

      - name: Remove Docker container
        run: docker rm singbox-ui-${{ matrix.arch }}-${{ matrix.version }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./filtered-bin/*.ipk
