name: Build packages
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build luci-app-singbox-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      # Извлекаем версию из тега (формат: vX.Y.Z)
      - name: Extract version
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version: $VERSION"

      # Подменяем версию в Makefile
      - name: Update version in Makefile
        run: |
          sed -i "s/^PKG_VERSION:=.*/PKG_VERSION:=${{ steps.extract_version.outputs.version }}/" Makefile
          sed -i "s/^PKG_RELEASE:=.*/PKG_RELEASE:=1/" Makefile
          cat Makefile

      - name: Build and push
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          tags: singbox-ui:ci

      - name: Create Docker container
        run: docker create --name singbox-ui singbox-ui:ci

      - name: Copy file from Docker container
        run: |
          docker cp singbox-ui:/builder/bin/packages/x86_64/luci/. ./bin/
          
      - name: Filter IPK files
        run: |
          mkdir -p ./filtered-bin
          cp ./bin/luci-app-singbox-ui*.ipk ./filtered-bin/luci-app-singbox-ui-${{ steps.extract_version.outputs.version }}.ipk

      - name: Remove Docker container
        run: docker rm singbox-ui

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: ./filtered-bin/*.ipk
