name: Build luci-app-singbox-ui

on:
  push:
    tags:
      - v*

jobs:
  build:
    strategy:
      matrix:
        include:
          - sdk_version: snapshot
            target: x86
            subtarget: 64
            arch: x86_64

          - sdk_version: v23.05.5
            target: x86
            subtarget: 64
            arch: x86_64

          - sdk_version: v24.10.1
            target: x86
            subtarget: 64
            arch: x86_64

          - sdk_version: snapshot
            target: armvirt
            subtarget: 32
            arch: arm_cortex-a7

          - sdk_version: v23.05.5
            target: armvirt
            subtarget: 32
            arch: arm_cortex-a7

          - sdk_version: snapshot
            target: ramips
            subtarget: mt76x8
            arch: mipsel_24kc

          - sdk_version: v23.05.5
            target: ramips
            subtarget: mt76x8
            arch: mipsel_24kc

    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} (${{ matrix.sdk_version }})

    steps:
      - uses: actions/checkout@v4

      - name: Build using Docker
        run: |
          docker build . \
            -f Dockerfile.builder \
            --build-arg SDK_VERSION=${{ matrix.sdk_version }} \
            --build-arg TARGET=${{ matrix.target }} \
            --build-arg SUBTARGET=${{ matrix.subtarget }} \
            -t luci-app-singbox-ui:${{ matrix.arch }}

      - name: Create container and extract result
        run: |
          docker create --name builder luci-app-singbox-ui:${{ matrix.arch }}
          docker cp builder:/builder/sdk/bin/packages/${{ matrix.target }}_${{ matrix.subtarget }}/luci/luci-app-singbox-ui*.ipk ./luci-app-singbox-ui_${{ matrix.arch }}_${{ matrix.sdk_version }}.ipk
          docker rm builder

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./luci-app-singbox-ui_*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
