# .github/workflows/singbox-ui-build.yml
name: Build luci-app-singbox-ui

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version match
        run: |
          LUCI_APP_SINGBOX_UI_VERSION=$(grep '^PKG_VERSION:=' luci-app-singbox-ui/Makefile | cut -d '=' -f2 | tr -d ' ')
          TAG_VERSION=${GITHUB_REF#refs/tags/v}

          echo "Luci-app-singbox-ui version: $LUCI_APP_SINGBOX_UI_VERSION"
          echo "Tag version: $TAG_VERSION"

          if [ "$LUCI_APP_SINGBOX_UI_VERSION" != "$TAG_VERSION" ]; then
            echo "❌ Version mismatch"
            exit 1
          fi

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: singbox-ui:ci

      - name: Create container and extract IPKs
        run: |
          docker create --name singbox-ui singbox-ui:ci
          docker cp singbox-ui:/builder/bin/packages/x86_64/luci/. ./bin/
          docker rm singbox-ui

      - name: Filter output
        run: |
          mkdir -p ./filtered-bin
          cp ./bin/luci-app-singbox-ui*.ipk ./filtered-bin/luci-app-singbox-ui.ipk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./filtered-bin/*.ipk
