name: Build packages

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86_64, arm_cortex-a7, mipsel_24kc]
        sdk_version: [snapshot, v23.05.5, v24.10.1]

    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg ARCH=${{ matrix.arch }} \
            --build-arg SDK_VERSION=${{ matrix.sdk_version }} \
            -t singbox-ui:${{ matrix.arch }}-${{ matrix.sdk_version }} .

      - name: Create container
        run: docker create --name singbox-ui singbox-ui:${{ matrix.arch }}-${{ matrix.sdk_version }}

      - name: Copy IPK from container
        run: |
          mkdir -p ./bin
          docker cp singbox-ui:/builder/bin/packages/${{ matrix.arch }}/luci/ ./bin/

      - name: Filter IPK files
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p ./filtered-bin
          cp ./bin/luci-app-singbox-ui*.ipk ./filtered-bin/luci-app-singbox-ui_${{ matrix.arch }}_${{ matrix.sdk_version }}.ipk

      - name: Remove container
        run: docker rm singbox-ui

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./filtered-bin/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
