name: Build packages

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
          - name: openwrt-24.10.1
            sdk_url: https://downloads.openwrt.org/releases/24.10.1/targets/x86/64/openwrt-sdk-24.10.1-x86-64_gcc-13.2.0_musl.Linux-x86_64.tar.xz
            arch: x86_64
            sdk_dir: openwrt-sdk-24.10.1-x86-64_gcc-13.2.0_musl.Linux-x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Download OpenWrt SDK
        run: |
          wget "${{ matrix.build.sdk_url }}" -O sdk.tar.xz
          tar -xf sdk.tar.xz

      - name: Prepare SDK
        run: |
          cd ${{ matrix.build.sdk_dir }}
          ./scripts/feeds update -a
          ./scripts/feeds install luci-base
          mkdir -p package/feeds/luci/
          cp -r $GITHUB_WORKSPACE/luci-app-singbox-ui package/feeds/luci/

      - name: Build package
        run: |
          cd ${{ matrix.build.sdk_dir }}
          make defconfig
          make package/luci-app-singbox-ui/compile V=s -j$(nproc)

      - name: Collect IPK
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          find ${{ matrix.build.sdk_dir }}/bin/packages/ -name 'luci-app-singbox-ui*.ipk' -exec cp {} $GITHUB_WORKSPACE/output/luci-app-singbox-ui_${{ matrix.build.name }}.ipk \;

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/*.ipk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
